// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	search: {
		/**
		 * S​e​a​r​c​h
		 */
		submit: string
	}
	filter: {
		/**
		 * O​p​e​n​ ​F​i​l​t​e​r
		 */
		open: string
	}
	pokedex: {
		/**
		 * S​h​o​w​ ​m​o​r​e
		 */
		loadMore: string
	}
}

export type TranslationFunctions = {
	search: {
		/**
		 * Search
		 */
		submit: () => LocalizedString
	}
	filter: {
		/**
		 * Open Filter
		 */
		open: () => LocalizedString
	}
	pokedex: {
		/**
		 * Show more
		 */
		loadMore: () => LocalizedString
	}
}

export type Formatters = {}
