// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	search: {
		/**
		 * S​e​a​r​c​h
		 */
		submit: string
	}
	filter: {
		/**
		 * O​p​e​n​ ​F​i​l​t​e​r
		 */
		open: string
	}
	pokedex: {
		/**
		 * S​h​o​w​ ​m​o​r​e
		 */
		loadMore: string
		/**
		 * N​o​ ​r​e​s​u​l​t​s​ ​f​o​u​n​d​.
		 */
		noResults: string
	}
	pokemon: {
		/**
		 * O​v​e​r​v​i​e​w
		 */
		overview: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		description: string
		/**
		 * I​n​f​o
		 */
		info: string
		/**
		 * H​e​i​g​h​t
		 */
		height: string
		/**
		 * W​e​i​g​h​t
		 */
		weight: string
		/**
		 * A​b​i​l​i​t​i​e​s
		 */
		abilities: string
		/**
		 * S​t​a​t​s
		 */
		stats: string
		/**
		 * B​a​s​e​ ​S​t​a​t​s
		 */
		baseStats: string
		/**
		 * E​v​o​l​u​t​i​o​n
		 */
		evolution: string
		stat: {
			/**
			 * H​P
			 */
			hp: string
			/**
			 * A​T​K
			 */
			atk: string
			/**
			 * D​E​F
			 */
			def: string
			/**
			 * S​p​A
			 */
			spa: string
			/**
			 * S​p​D
			 */
			spd: string
			/**
			 * S​P​D
			 */
			spe: string
		}
	}
}

export type TranslationFunctions = {
	search: {
		/**
		 * Search
		 */
		submit: () => LocalizedString
	}
	filter: {
		/**
		 * Open Filter
		 */
		open: () => LocalizedString
	}
	pokedex: {
		/**
		 * Show more
		 */
		loadMore: () => LocalizedString
		/**
		 * No results found.
		 */
		noResults: () => LocalizedString
	}
	pokemon: {
		/**
		 * Overview
		 */
		overview: () => LocalizedString
		/**
		 * Description
		 */
		description: () => LocalizedString
		/**
		 * Info
		 */
		info: () => LocalizedString
		/**
		 * Height
		 */
		height: () => LocalizedString
		/**
		 * Weight
		 */
		weight: () => LocalizedString
		/**
		 * Abilities
		 */
		abilities: () => LocalizedString
		/**
		 * Stats
		 */
		stats: () => LocalizedString
		/**
		 * Base Stats
		 */
		baseStats: () => LocalizedString
		/**
		 * Evolution
		 */
		evolution: () => LocalizedString
		stat: {
			/**
			 * HP
			 */
			hp: () => LocalizedString
			/**
			 * ATK
			 */
			atk: () => LocalizedString
			/**
			 * DEF
			 */
			def: () => LocalizedString
			/**
			 * SpA
			 */
			spa: () => LocalizedString
			/**
			 * SpD
			 */
			spd: () => LocalizedString
			/**
			 * SPD
			 */
			spe: () => LocalizedString
		}
	}
}

export type Formatters = {}
